# Generated by Django 6.1 on 2026-08-27 12:53

import combine.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CombineOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('pdf_merge', 'PDF Merge'), ('split_pdf', 'Split PDF'), ('organize_pdf', 'Organize PDF'), ('image_merge', 'Image Merge'), ('image_to_pdf', 'Image to PDF'), ('image_convert', 'Image Converter'), ('word_merge', 'Word Merge'), ('pdf_to_word', 'PDF to Word'), ('word_to_pdf', 'Word to PDF'), ('compress_pdf', 'PDF Compress'), ('rotate_pdf', 'Rotate PDF'), ('nup_pdf', 'N-up PDF'), ('watermark_pdf', 'Watermark PDF'), ('pdf_color_enhance', 'PDF Color Enhance'), ('pdf_to_excel', 'PDF to Excel'), ('excel_to_pdf', 'Excel to PDF')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('input_files', models.JSONField(blank=True, default=list, help_text='List of input file names or paths.')),
                ('input_count', models.PositiveSmallIntegerField(default=0)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=combine.models.combine_upload_path)),
                ('output_name', models.CharField(blank=True, default='', max_length=500)),
                ('output_size', models.PositiveBigIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=dict, help_text='Operation-specific settings stored as JSON.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'combine_operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
