# Generated by Django 6.1 on 2026-08-15 09:46

import combine.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CombineOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('pdf_merge', 'PDF Merge'), ('pdf_split', 'PDF Split'), ('image_merge', 'Image Merge'), ('image_to_pdf', 'Image to PDF'), ('word_merge', 'Word Merge'), ('pdf_to_word', 'PDF to Word'), ('word_to_pdf', 'Word to PDF'), ('compress_pdf', 'Compress PDF'), ('rotate_pdf', 'Rotate PDF'), ('watermark_pdf', 'Watermark PDF')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_files', models.JSONField(default=list)),
                ('input_count', models.PositiveSmallIntegerField(default=0)),
                ('output_file', models.FileField(blank=True, null=True, upload_to=combine.models.combine_upload_path)),
                ('output_name', models.CharField(blank=True, max_length=500)),
                ('output_size', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'combine_operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
