# Generated by Django 6.1 on 2026-08-27 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='combineoperation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combine_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='combineoperation',
            index=models.Index(fields=['user', '-created_at'], name='combine_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='combineoperation',
            index=models.Index(fields=['user', 'operation_type'], name='combine_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='combineoperation',
            index=models.Index(fields=['user', 'status'], name='combine_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='combineoperation',
            index=models.Index(fields=['operation_type', 'created_at'], name='combine_type_created_idx'),
        ),
    ]
