# Generated by Django 6.1 on 2026-09-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combine', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combineoperation',
            name='operation_type',
            field=models.CharField(choices=[('pdf_merge', 'PDF Merge'), ('split_pdf', 'Split PDF'), ('organize_pdf', 'Organize PDF'), ('image_merge', 'Image Merge'), ('image_to_pdf', 'Image to PDF'), ('image_convert', 'Image Converter'), ('image_compress', 'Image Compressor'), ('word_merge', 'Word Merge'), ('pdf_to_word', 'PDF to Word'), ('word_to_pdf', 'Word to PDF'), ('compress_pdf', 'PDF Compress'), ('rotate_pdf', 'Rotate PDF'), ('nup_pdf', 'N-up PDF'), ('watermark_pdf', 'Watermark PDF'), ('pdf_color_enhance', 'PDF Color Enhance'), ('pdf_to_excel', 'PDF to Excel'), ('excel_to_pdf', 'Excel to PDF')], db_index=True, max_length=40),
        ),
    ]
