# Generated by Django 6.1 on 2026-08-21 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combine', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='combineoperation',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='combineoperation',
            name='input_files',
            field=models.JSONField(blank=True, default=list, help_text='List of input file paths or names.'),
        ),
        migrations.AlterField(
            model_name='combineoperation',
            name='operation_type',
            field=models.CharField(choices=[('pdf_merge', 'PDF Merge'), ('split_pdf', 'Split PDF'), ('image_merge', 'Image Merge'), ('image_to_pdf', 'Image to PDF'), ('image_convert', 'Image Converter'), ('word_merge', 'Word Merge'), ('pdf_to_word', 'PDF to Word'), ('word_to_pdf', 'Word to PDF'), ('compress_pdf', 'PDF Compress'), ('rotate_pdf', 'Rotate PDF'), ('organize_pdf', 'Organize PDF'), ('watermark_pdf', 'Watermark PDF'), ('pdf_color_enhance', 'PDF Color Enhance'), ('nup_pdf', 'N-up PDF')], max_length=30),
        ),
        migrations.AlterField(
            model_name='combineoperation',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Operation-specific settings.'),
        ),
        migrations.AlterField(
            model_name='combineoperation',
            name='output_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='combineoperation',
            name='output_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='combineoperation',
            index=models.Index(fields=['user', '-created_at'], name='combine_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='combineoperation',
            index=models.Index(fields=['user', 'operation_type'], name='combine_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='combineoperation',
            index=models.Index(fields=['user', 'status'], name='combine_user_status_idx'),
        ),
    ]
