# Generated by Django 6.1 on 2026-08-21 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combine', '0003_alter_combineoperation_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='combineoperation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='combineoperation',
            name='input_files',
            field=models.JSONField(blank=True, default=list, help_text='List of input file names or paths.'),
        ),
        migrations.AlterField(
            model_name='combineoperation',
            name='operation_type',
            field=models.CharField(choices=[('pdf_merge', 'PDF Merge'), ('split_pdf', 'Split PDF'), ('organize_pdf', 'Organize PDF'), ('image_merge', 'Image Merge'), ('image_to_pdf', 'Image to PDF'), ('image_convert', 'Image Converter'), ('word_merge', 'Word Merge'), ('pdf_to_word', 'PDF to Word'), ('word_to_pdf', 'Word to PDF'), ('compress_pdf', 'PDF Compress'), ('rotate_pdf', 'Rotate PDF'), ('nup_pdf', 'N-up PDF'), ('watermark_pdf', 'Watermark PDF'), ('pdf_color_enhance', 'PDF Color Enhance'), ('pdf_to_excel', 'PDF to Excel'), ('excel_to_pdf', 'Excel to PDF')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='combineoperation',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Operation-specific settings stored as JSON.'),
        ),
        migrations.AlterField(
            model_name='combineoperation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='combineoperation',
            index=models.Index(fields=['operation_type', 'created_at'], name='combine_type_created_idx'),
        ),
    ]
