# Generated by Django 6.1 on 2026-08-15
import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyUsageStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(),
                ),
                (
                    "translations_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "translation_chars",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "text_to_text_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "text_to_speech_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "speech_to_text_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "speech_to_speech_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "tools_usage_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "documents_uploaded",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "document_pages",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "combine_operations",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "session_duration",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_usage_stats",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),

        migrations.CreateModel(
            name="WeeklyUsageStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(),
                ),
                (
                    "week",
                    models.PositiveSmallIntegerField(),
                ),
                (
                    "translations_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "translation_chars",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "tools_usage_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "documents_uploaded",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "document_pages",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "combine_operations",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "session_duration",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "weekly_usage_stats",
                "ordering": ["-year", "-week"],
                "unique_together": {("user", "year", "week")},
            },
        ),

        migrations.CreateModel(
            name="MonthlyUsageStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(),
                ),
                (
                    "translations_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "translation_chars",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "tools_usage_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "documents_uploaded",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "document_pages",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "combine_operations",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "session_duration",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "monthly_usage_stats",
                "ordering": ["-year", "-month"],
                "unique_together": {("user", "year", "month")},
            },
        ),

        migrations.CreateModel(
            name="LanguageUsageStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_lang",
                    models.CharField(max_length=10),
                ),
                (
                    "target_lang",
                    models.CharField(max_length=10),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "language_usage_stats",
                "ordering": ["-usage_count"],
                "unique_together": {
                    ("user", "source_lang", "target_lang")
                },
            },
        ),

        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("translate", "Translate"),
                            ("tts", "Text to Speech"),
                            ("stt", "Speech to Text"),
                            ("tool_use", "Tool Use"),
                            ("document_upload", "Document Upload"),
                            ("document_download", "Document Download"),
                            ("combine", "File Combine"),
                            ("settings_change", "Settings Change"),
                            ("profile_update", "Profile Update"),
                            ("password_change", "Password Change"),
                            ("otp_enable", "OTP Enabled"),
                            ("otp_disable", "OTP Disabled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=500,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_activity_logs",
                "ordering": ["-created_at"],
            },
        ),

        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["user", "-created_at"],
                name="user_activit_user_id_6e7d50_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["user", "activity_type", "-created_at"],
                name="user_activit_user_id_2f9e6b_idx",
            ),
        ),
    ]