# Generated by Django 6.1 on 2026-08-27 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('translations_count', models.PositiveIntegerField(default=0)),
                ('translation_chars', models.PositiveIntegerField(default=0)),
                ('text_to_text_count', models.PositiveIntegerField(default=0)),
                ('text_to_speech_count', models.PositiveIntegerField(default=0)),
                ('speech_to_text_count', models.PositiveIntegerField(default=0)),
                ('speech_to_speech_count', models.PositiveIntegerField(default=0)),
                ('tools_usage_count', models.PositiveIntegerField(default=0)),
                ('documents_uploaded', models.PositiveIntegerField(default=0)),
                ('document_pages', models.PositiveIntegerField(default=0)),
                ('combine_operations', models.PositiveIntegerField(default=0)),
                ('session_duration', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_usage_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LanguageUsageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_lang', models.CharField(max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'language_usage_stats',
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyUsageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('translations_count', models.PositiveIntegerField(default=0)),
                ('translation_chars', models.PositiveIntegerField(default=0)),
                ('tools_usage_count', models.PositiveIntegerField(default=0)),
                ('documents_uploaded', models.PositiveIntegerField(default=0)),
                ('combine_operations', models.PositiveIntegerField(default=0)),
                ('session_duration', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'monthly_usage_stats',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('translate', 'Translate'), ('tts', 'Text to Speech'), ('stt', 'Speech to Text'), ('tool_use', 'Tool Use'), ('document_upload', 'Document Upload'), ('document_download', 'Document Download'), ('combine', 'File Combine'), ('settings_change', 'Settings Change'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('otp_enable', 'OTP Enabled'), ('otp_disable', 'OTP Disabled')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyUsageStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('week', models.PositiveSmallIntegerField()),
                ('translations_count', models.PositiveIntegerField(default=0)),
                ('translation_chars', models.PositiveIntegerField(default=0)),
                ('tools_usage_count', models.PositiveIntegerField(default=0)),
                ('documents_uploaded', models.PositiveIntegerField(default=0)),
                ('combine_operations', models.PositiveIntegerField(default=0)),
                ('session_duration', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'weekly_usage_stats',
                'ordering': ['-year', '-week'],
            },
        ),
    ]
