# Generated by Django 6.1 on 2026-08-27 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusagestats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languageusagestats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyusagestats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyusagestats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyusagestats',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='languageusagestats',
            unique_together={('user', 'source_lang', 'target_lang')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyusagestats',
            unique_together={('user', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-created_at'], name='user_activi_user_id_543519_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'activity_type', '-created_at'], name='user_activi_user_id_d5c268_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyusagestats',
            unique_together={('user', 'year', 'week')},
        ),
    ]
