# Generated by Django 6.1 on 2026-08-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='user_activit_user_id_6e7d50_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractivitylog',
            name='user_activit_user_id_2f9e6b_idx',
        ),
        migrations.RemoveField(
            model_name='monthlyusagestats',
            name='document_pages',
        ),
        migrations.RemoveField(
            model_name='weeklyusagestats',
            name='document_pages',
        ),
    ]
