# Generated by Django 6.1 on 2026-08-15 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_type', models.CharField(choices=[('translation', 'Translation'), ('tool', 'Tool'), ('document', 'Document')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('source_app', models.CharField(max_length=50)),
                ('source_model', models.CharField(max_length=50)),
                ('source_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'unified_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
