# Generated by Django 6.1 on 2026-08-27 12:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_type', models.CharField(choices=[('translate', 'Translation'), ('tools', 'Tools'), ('documents', 'Documents'), ('combine', 'Combine')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('source_app', models.CharField(blank=True, max_length=50)),
                ('source_model', models.CharField(blank=True, max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='history_outputs/%Y/%m/')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('processing', 'Processing')], db_index=True, default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unified History',
                'verbose_name_plural': 'Unified Histories',
                'db_table': 'unified_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
