# Generated by Django 6.1 on 2026-08-15 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='unifiedhistory',
            index=models.Index(fields=['user', '-created_at'], name='unified_his_user_id_566c45_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedhistory',
            index=models.Index(fields=['user', 'history_type', '-created_at'], name='unified_his_user_id_00b4e4_idx'),
        ),
    ]
