# Generated by Django 6.1 on 2026-08-21 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unifiedhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Unified History', 'verbose_name_plural': 'Unified Histories'},
        ),
        migrations.AddField(
            model_name='unifiedhistory',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='history_outputs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='unifiedhistory',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('processing', 'Processing')], db_index=True, default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='unifiedhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='unifiedhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='unifiedhistory',
            name='history_type',
            field=models.CharField(choices=[('translate', 'Translation'), ('tools', 'Tools'), ('documents', 'Documents'), ('combine', 'Combine')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='unifiedhistory',
            name='source_app',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='unifiedhistory',
            name='source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='unifiedhistory',
            name='source_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='unifiedhistory',
            index=models.Index(fields=['user', 'status'], name='unified_his_user_id_293328_idx'),
        ),
    ]
