# Generated by Django 6.1 on 2026-08-15 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('default_page', models.CharField(choices=[('translate', 'Translate'), ('tools', 'Tools'), ('documents', 'Documents'), ('history', 'History'), ('dashboard', 'Dashboard')], default='translate', max_length=20)),
                ('show_tips', models.BooleanField(default=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('auto_detect_language', models.BooleanField(default=True)),
                ('show_transliteration', models.BooleanField(default=False)),
                ('show_definitions', models.BooleanField(default=False)),
                ('show_examples', models.BooleanField(default=False)),
                ('formal_tone', models.BooleanField(default=False)),
                ('auto_play_tts', models.BooleanField(default=False)),
                ('tts_volume', models.PositiveSmallIntegerField(default=80)),
                ('stt_language', models.CharField(default='en', max_length=10)),
                ('microphone_sensitivity', models.PositiveSmallIntegerField(default=50)),
                ('history_retention_days', models.PositiveSmallIntegerField(default=365)),
                ('clear_history_on_exit', models.BooleanField(default=False)),
                ('incognito_mode', models.BooleanField(default=False)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('sound_effects', models.BooleanField(default=True)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='medium', max_length=10)),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduce_animations', models.BooleanField(default=False)),
                ('default_export_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('txt', 'Text'), ('html', 'HTML')], default='pdf', max_length=10)),
                ('include_watermark', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(blank=True, default='Translated by quill', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='AutoSaveData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_type', models.CharField(choices=[('translate', 'Translation Draft'), ('tool', 'Tool Draft'), ('document', 'Document Settings')], max_length=20)),
                ('draft_data', models.JSONField(default=dict)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'autosave_data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'blocked_languages',
            },
        ),
        migrations.CreateModel(
            name='CustomShortcut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('key_combo', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'custom_shortcuts',
            },
        ),
    ]
