# Generated by Django 6.1 on 2026-08-15 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autosavedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autosave_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockedlanguage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_languages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customshortcut',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_shortcuts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='autosavedata',
            unique_together={('user', 'draft_type', 'page_url')},
        ),
        migrations.AlterUniqueTogether(
            name='blockedlanguage',
            unique_together={('user', 'language_code')},
        ),
        migrations.AlterUniqueTogether(
            name='customshortcut',
            unique_together={('user', 'action')},
        ),
    ]
