# Generated by Django 6.1 on 2026-08-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='allow_analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='auto_save',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='auto_swap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='auto_translate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cache_size',
            field=models.CharField(choices=[('small', 'Small (50MB)'), ('medium', 'Medium (200MB)'), ('large', 'Large (500MB)')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_engine',
            field=models.CharField(choices=[('google', 'Google Translate'), ('deepl', 'DeepL'), ('microsoft', 'Microsoft'), ('myMemory', 'MyMemory')], default='google', max_length=30),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='export_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('txt', 'Text'), ('html', 'HTML')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='formality_level',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('formal', 'Formal'), ('informal', 'Informal')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='preserve_formatting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='save_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='share_usage_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='show_animations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='show_original_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='source_language',
            field=models.CharField(default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='target_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='translation_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='translation_speed',
            field=models.CharField(choices=[('standard', 'Standard'), ('fast', 'Fast'), ('quality', 'High Quality')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='translation_style',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('formal', 'Formal'), ('casual', 'Casual'), ('creative', 'Creative')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='weekly_report',
            field=models.BooleanField(default=False),
        ),
    ]
