# Generated by Django 6.1 on 2026-08-22 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_appsettings_allow_analytics_appsettings_auto_save_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name': 'App Settings', 'verbose_name_plural': 'App Settings'},
        ),
        migrations.RenameField(
            model_name='appsettings',
            old_name='high_contrast',
            new_name='developer_mode',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='reduce_animations',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 22, 19, 23, 0, 771763, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appsettings',
            name='tts_voice',
            field=models.CharField(default='en-US-AriaNeural', max_length=100),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='default_page',
            field=models.CharField(choices=[('translate', 'Translate'), ('tools', 'Tools'), ('documents', 'Documents'), ('history', 'History'), ('dashboard', 'Dashboard'), ('about', 'About'), ('settings', 'Settings')], default='translate', max_length=20),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='export_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('txt', 'Plain Text'), ('html', 'HTML')], default='pdf', max_length=10),
        ),
    ]
