# Generated by Django 6.1 on 2026-08-15 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tool_type', models.CharField(choices=[('number_converter', 'Number Converter'), ('currency_converter', 'Currency Converter'), ('unit_converter', 'Unit Converter'), ('data_storage_converter', 'Data Storage Converter'), ('electrical_converter', 'Electrical Converter'), ('health_calculator', 'Health Calculator'), ('specific_calculator', 'Specific Calculator')], max_length=30)),
                ('input_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'saved_calculations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_type', models.CharField(choices=[('number_converter', 'Number Converter'), ('currency_converter', 'Currency Converter'), ('unit_converter', 'Unit Converter'), ('data_storage_converter', 'Data Storage Converter'), ('electrical_converter', 'Electrical Converter'), ('health_calculator', 'Health Calculator'), ('specific_calculator', 'Specific Calculator')], max_length=30)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tools_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'currency_rates',
                'unique_together': {('base_currency', 'target_currency')},
            },
        ),
    ]
