# Generated by Django 6.1 on 2026-08-15 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('source_lang', models.CharField(max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('folder', models.CharField(blank=True, default='General', max_length=100)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favorite_translations',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('native_name', models.CharField(blank=True, max_length=100)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpeechProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
                ('voice_id', models.CharField(max_length=100)),
                ('voice_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('speed', models.FloatField(default=1.0)),
                ('pitch', models.FloatField(default=1.0)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'speech_profiles',
            },
        ),
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('source_lang', models.CharField(max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('mode', models.CharField(choices=[('text_to_text', 'Text to Text'), ('text_to_speech', 'Text to Speech'), ('speech_to_text', 'Speech to Text'), ('speech_to_speech', 'Speech to Speech')], default='text_to_text', max_length=20)),
                ('engine', models.CharField(choices=[('grok', 'Grok AI'), ('google', 'Google Translate'), ('deepl', 'DeepL')], default='grok', max_length=20)),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('audio_duration', models.FloatField(blank=True, null=True)),
                ('detected_source_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'translation_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
