# Generated by Django 6.1 on 2026-08-27 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritetranslation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speechprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoritetranslation',
            unique_together={('user', 'source_text', 'source_lang', 'target_lang')},
        ),
        migrations.AlterUniqueTogether(
            name='speechprofile',
            unique_together={('user', 'language')},
        ),
        migrations.AddIndex(
            model_name='translationhistory',
            index=models.Index(fields=['user', '-created_at'], name='translation_user_id_fc82bf_idx'),
        ),
        migrations.AddIndex(
            model_name='translationhistory',
            index=models.Index(fields=['user', 'is_favorite'], name='translation_user_id_a172c7_idx'),
        ),
        migrations.AddIndex(
            model_name='translationhistory',
            index=models.Index(fields=['source_lang', 'target_lang'], name='translation_source__cacfce_idx'),
        ),
    ]
