# Generated by Django 6.1 on 2026-08-23 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='translationhistory',
            name='auto_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationhistory',
            name='formality_level',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('formal', 'Formal'), ('informal', 'Informal')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='translationhistory',
            name='preserve_formatting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='translationhistory',
            name='show_original_text',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='translationhistory',
            name='translation_speed',
            field=models.CharField(choices=[('standard', 'Standard'), ('fast', 'Fast'), ('quality', 'High Quality')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='translationhistory',
            name='translation_style',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('formal', 'Formal'), ('casual', 'Casual'), ('creative', 'Creative')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='translationhistory',
            name='tts_voice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='engine',
            field=models.CharField(choices=[('grok', 'Grok AI'), ('google', 'Google Translate'), ('deepl', 'DeepL'), ('microsoft', 'Microsoft'), ('myMemory', 'MyMemory')], default='google', max_length=20),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
