# Generated by Django 6.1 on 2026-08-15 09:46

import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source_lang', models.CharField(max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('output_format', models.CharField(default='pdf', max_length=10)),
                ('preserve_formatting', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_templates',
            },
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('original_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('doc', 'Word Document (Old)'), ('txt', 'Plain Text'), ('rtf', 'Rich Text'), ('html', 'HTML'), ('md', 'Markdown'), ('csv', 'CSV'), ('xlsx', 'Excel'), ('pptx', 'PowerPoint'), ('epub', 'EPUB')], max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('page_count', models.PositiveIntegerField(default=0, help_text='Estimated pages')),
                ('source_lang', models.CharField(default='auto', max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('preserve_formatting', models.BooleanField(default=True)),
                ('translate_images', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('translating', 'Translating'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('status_message', models.CharField(blank=True, max_length=500)),
                ('translated_file', models.FileField(blank=True, null=True, upload_to=documents.models.document_upload_path)),
                ('translated_name', models.CharField(blank=True, max_length=500)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('txt', 'Plain Text'), ('html', 'HTML'), ('rtf', 'Rich Text')], default='pdf', max_length=10)),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text from document')),
                ('translated_text_preview', models.TextField(blank=True, help_text='First 2000 chars preview')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'document_uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
