# Generated by Django 6.1 on 2026-08-27 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['user', '-uploaded_at'], name='document_up_user_id_2aa726_idx'),
        ),
        migrations.AddIndex(
            model_name='documentupload',
            index=models.Index(fields=['user', 'status'], name='document_up_user_id_5d14c1_idx'),
        ),
    ]
