# Generated by Django 6.1 on 2026-08-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_monthly_translation_chars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monthly_translation_limit',
            field=models.PositiveIntegerField(default=50000),
        ),
    ]
