# Generated by Django 6.1 on 2026-08-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_monthly_translation_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_translation_chars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
