# Generated by Django 6.1 on 2026-08-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_monthly_translation_chars'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='show_animations',
            field=models.BooleanField(default=True),
        ),
    ]
