# Generated by Django 6.1 on 2026-08-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_compact_mode_user_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive updates via email'),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=False, help_text='Get browser push notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='translation_complete',
            field=models.BooleanField(default=True, help_text='Notify when translation finishes'),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_report',
            field=models.BooleanField(default=False, help_text='Get a weekly summary of your activity'),
        ),
    ]
