# Generated by Django 6.1 on 2026-08-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_analytics',
            field=models.BooleanField(default=True, help_text='Enable analytics to improve the platform'),
        ),
        migrations.AddField(
            model_name='user',
            name='share_usage_data',
            field=models.BooleanField(default=False, help_text='Help us improve by sharing anonymous usage data'),
        ),
    ]
