# Generated by Django 6.1 on 2026-08-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_allow_analytics_user_share_usage_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for SMS 2FA', max_length=15, null=True),
        ),
    ]
