# Generated by Django 6.1 on 2026-08-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_config',
            field=models.JSONField(blank=True, default=dict, help_text='API configuration (Base URL, API Key, etc.)'),
        ),
        migrations.AddField(
            model_name='user',
            name='cache_size',
            field=models.CharField(choices=[('small', 'Small (10 items)'), ('medium', 'Medium (20 items)'), ('large', 'Large (50 items)')], default='medium', help_text='Number of history items to store', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='developer_mode',
            field=models.BooleanField(default=False, help_text='Enable advanced debugging features'),
        ),
        migrations.AddField(
            model_name='user',
            name='export_format',
            field=models.CharField(choices=[('txt', 'Text File'), ('html', 'HTML'), ('docx', 'Word Document'), ('pdf', 'PDF')], default='pdf', help_text='Default export format', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='auto_save',
            field=models.BooleanField(default=True, help_text='Automatically save translation history'),
        ),
    ]
